name: Deploy to AWS Lightsail

on: 
  push:
    branches: [master]


jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: premission changed
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY }}
          script: |
            sudo chown -R ubuntu:www-data /var/www/html/myapp

      - name: check for frontend changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -E 'resources/js/|resources/css/|resources/views/|vite.config.js'; then
            echo "frontend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "frontend_changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Set up Node.js 20
        if: steps.check_for_frontend_changes.outputs.frontend_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY }}
          source: "./"
          target: "/var/www/html/myapp"


      - name: deploy changes
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY }}
          script: | 
              
              cd /var/www/html/myapp
              php artisan config:clear
              php artisan route:clear
              php artisan view:clear
              npm install
              npm run build
              sudo chown -R www-data:www-data /var/www/html/myapp
              sudo chmod -R 775 /var/www/html/myapp/storage /var/www/html/myapp/bootstrap/cache
              sudo systemctl restart apache2

              
